services:
  app:
    build: .
    container_name: mi-app
    ports:
      - "3000:3000"
    restart: always
    environment:
      NODE_ENV: development
      MONGODB_URI: "mongodb://root:facturacion@db:27017/f-devel?authSource=admin"
      SRI_ENVIRONMENT: 1  # 1=Pruebas, 2=Producción
      SRI_RECEPCION_URL_PRUEBAS: "https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl"
      SRI_RECEPCION_URL_PRODUCCION: "https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl"
      INVITATION_CODES: devel
      ALLOWED_RUCS: 1316037470001
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: mi-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: facturacion
    ports:
      - "27017:27017"
    volumes:
      - /DATA/Mongo:/data/db


